data_obs: Observed
backgrounds:
    BG:
        name: Backgrounds
        members:
            EMB: $\tau\tau$ bkg.
            TTL: $t\bar{t}$
            VVL: Diboson+single $t$ 
            ZL: $Z/\gamma^\ast\rightarrow\ell\ell$
            wFakes: W+jets
            W: W+jets
            QCD: QCD multijet
            jetFakes: Jet$\rightarrow\tau_{h}$
    H125:
        name: $H(125)$
        members:
            ggH125: $ggH(125)$
            qqH125: $qqH(125)$
            bbH125: $bbH(125)$
signals:
    bbh: $bb\phi$, $m_{\phi}=@MASS@\text{ GeV},\text{ }\sigma B = 1\text{ pb}$
    ggh_t: $gg\phi$ t-only, $m_{\phi}=@MASS@\text{ GeV},\text{ }\sigma B = 1\text{ pb}$
    ggh_b: $gg\phi$ b-only, $m_{\phi}=@MASS@\text{ GeV},\text{ }\sigma B = 1\text{ pb}$
    ggh_i: $gg\phi$ tb-interference, $m_{\phi}=@MASS@\text{ GeV},\text{ }\sigma B = 1\text{ pb}$
    VLQ_betaRd33_0_matched_M: VLQ signal (BM 1), $m_{U}=@MASS@\text{ TeV},\text{ }g_{U}=1$
    VLQ_betaRd33_0_matched_interference_M: VLQ interference (BM 1), $m_{U}=@MASS@\text{ TeV},\text{ }g_{U}=1$
    VLQ_betaRd33_minus1_matched_M: VLQ signal (BM 2), $m_{U}=@MASS@\text{ TeV},\text{ }g_{U}=1$
    VLQ_betaRd33_minus1_matched_interference_M: VLQ interference (BM 2), $m_{U}=@MASS@\text{ TeV},\text{ }g_{U}=1$
    VLQ_betaRd33_0_offdiag0_matched_M: VLQ signal (BM 3), $m_{U}=@MASS@\text{ TeV},\text{ }g_{U}=1$
    VLQ_betaRd33_0_offdiag0_matched_interference_M: VLQ interference (BM 3), $m_{U}=@MASS@\text{ TeV},\text{ }g_{U}=1$
categories:
    htt_tt_32_2016: $\tau_{h}\tau_{h}$, No b tag, 2016
    htt_tt_35_2016: $\tau_{h}\tau_{h}$, b tag, 2016
    htt_tt_32_2017: $\tau_{h}\tau_{h}$, No b tag, 2017
    htt_tt_35_2017: $\tau_{h}\tau_{h}$, b tag, 2017
    htt_tt_32_2018: $\tau_{h}\tau_{h}$, No b tag, 2018
    htt_tt_35_2018: $\tau_{h}\tau_{h}$, b tag, 2018
