data_obs: Observed
backgrounds:
    BG:
        name: Backgrounds
        members:
            EMB: $\tau\tau$ bkg.
            TTL: $t\bar{t}$
            VVL: Diboson+single $t$ 
            ZL: $Z/\gamma^\ast\rightarrow\ell\ell$
            wFakes: W+jets
            jetFakes: Jet$\rightarrow\tau_{h}$
    H125:
        name: $H(125)$
        members:
            ggH125: $ggH(125)$
            qqH125: $qqH(125)$
            bbH125: $bbH(125)$
signals:
    bbh: $bb\phi(@MASS@)$
    ggh_t: $gg\phi(@MASS@)$ t-only
    ggh_b: $gg\phi(@MASS@)$ b-only
    ggh_i: $gg\phi(@MASS@)$ tb-interference
categories:
    htt_tt_35_2018: $\tau_{h}\tau_{h}$, b tag, 2018
