#! /bin/bash

PAPERREPO=${1}
pushd submission_preparation;
rsync -av --progress ${PAPERREPO}/Auxx/mssm_model-independent_combined_ggH_freezebbH_cmb.pdf Aux_Figure_037.pdf
rsync -av --progress ${PAPERREPO}/Auxx/mssm_model-independent_combined_bbH_freezeggH_cmb.pdf Aux_Figure_038.pdf
rsync -av --progress ${PAPERREPO}/Auxx/mssm_model-independent_combined_ggH_Tonly_cmb.pdf Aux_Figure_039.pdf
rsync -av --progress ${PAPERREPO}/Auxx/mssm_model-independent_combined_ggH_Bonly_cmb.pdf Aux_Figure_040.pdf
rsync -av --progress ${PAPERREPO}/Auxx/significance_plot_ggH.pdf Aux_Figure_031.pdf
rsync -av --progress ${PAPERREPO}/Auxx/significance_plot_bbH.pdf Aux_Figure_032.pdf
rsync -av --progress ${PAPERREPO}/Auxx/significance_plot_ggH_freezebbH.pdf Aux_Figure_033.pdf
rsync -av --progress ${PAPERREPO}/Auxx/significance_plot_bbH_freezeggH.pdf Aux_Figure_034.pdf
rsync -av --progress ${PAPERREPO}/Auxx/significance_plot_ggH_Tonly.pdf Aux_Figure_035.pdf
rsync -av --progress ${PAPERREPO}/Auxx/significance_plot_ggH_Bonly.pdf Aux_Figure_036.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_qqH_95.pdf Aux_Figure_064.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_60.pdf Aux_Figure_065.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_60.pdf Aux_Figure_066.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_80.pdf Aux_Figure_067.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_80.pdf Aux_Figure_068.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_95.pdf Aux_Figure_069.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_95.pdf Aux_Figure_070.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_100.pdf Aux_Figure_071.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_100.pdf Aux_Figure_072.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_120.pdf Aux_Figure_073.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_120.pdf Aux_Figure_074.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_125.pdf Aux_Figure_075.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_125.pdf Aux_Figure_076.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_130.pdf Aux_Figure_077.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_130.pdf Aux_Figure_078.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_140.pdf Aux_Figure_079.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_140.pdf Aux_Figure_080.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_160.pdf Aux_Figure_081.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_160.pdf Aux_Figure_082.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_180.pdf Aux_Figure_083.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_180.pdf Aux_Figure_084.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_H_200.pdf Aux_Figure_085.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_A_200.pdf Aux_Figure_086.pdf
rsync -av --progress ${PAPERREPO}/Auxx/vlq_bm_3.pdf Aux_Figure_092.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH80.pdf Aux_Figure_041.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH95.pdf Aux_Figure_042.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH120.pdf Aux_Figure_043.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH130.pdf Aux_Figure_044.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH140.pdf Aux_Figure_045.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH180.pdf Aux_Figure_046.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH200.pdf Aux_Figure_047.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH300.pdf Aux_Figure_048.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH350.pdf Aux_Figure_049.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH400.pdf Aux_Figure_050.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH450.pdf Aux_Figure_051.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH600.pdf Aux_Figure_052.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH700.pdf Aux_Figure_053.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH800.pdf Aux_Figure_054.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH900.pdf Aux_Figure_055.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH1400.pdf Aux_Figure_056.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH1600.pdf Aux_Figure_057.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH1800.pdf Aux_Figure_058.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH2000.pdf Aux_Figure_059.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH2300.pdf Aux_Figure_060.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH2600.pdf Aux_Figure_061.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH2900.pdf Aux_Figure_062.pdf
rsync -av --progress ${PAPERREPO}/Auxx/likelihood_scan_ggH-bbH_mH3200.pdf Aux_Figure_063.pdf
rsync -av --progress ${PAPERREPO}/Figure_0{08-,10-,11-,12-,13-a,13-b}*.pdf .
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_1000.pdf Aux_Figure_099.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_2000.pdf Aux_Figure_100.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_3000.pdf Aux_Figure_101.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_4000.pdf Aux_Figure_102.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_5000.pdf Aux_Figure_103.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_minus1_1000.pdf Aux_Figure_104.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_minus1_2000.pdf Aux_Figure_105.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_minus1_3000.pdf Aux_Figure_106.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_minus1_4000.pdf Aux_Figure_107.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_minus1_5000.pdf Aux_Figure_108.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_offdiag0_1000.pdf Aux_Figure_109.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_offdiag0_2000.pdf Aux_Figure_110.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_offdiag0_3000.pdf Aux_Figure_111.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_offdiag0_4000.pdf Aux_Figure_112.pdf
rsync -av --progress ${PAPERREPO}/Auxx/scan_betaRd33_0_offdiag0_5000.pdf Aux_Figure_113.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_mt_tot_postfit_em_32.pdf Aux_Figure_025.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_mt_tot_postfit_em_34.pdf Aux_Figure_026.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_mt_tot_postfit_em_35.pdf Aux_Figure_027.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_mt_tot_postfit_em_37.pdf Aux_Figure_028.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_mt_tot_postfit_lt_33.pdf Aux_Figure_029.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_mt_tot_postfit_lt_36.pdf Aux_Figure_030.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_em_132.pdf Aux_Figure_011.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_em_232.pdf Aux_Figure_012.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_em_332.pdf Aux_Figure_013.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_em_432.pdf Aux_Figure_014.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_em_35_m_sv.pdf Aux_Figure_010.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_lt_132.pdf Aux_Figure_016.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_lt_232.pdf Aux_Figure_017.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_lt_332.pdf Aux_Figure_018.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_lt_432.pdf Aux_Figure_019.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_lt_35_m_sv.pdf Aux_Figure_015.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_tt_132.pdf Aux_Figure_021.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_tt_232.pdf Aux_Figure_022.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_tt_332.pdf Aux_Figure_023.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_tt_432.pdf Aux_Figure_024.pdf
rsync -av --progress ${PAPERREPO}/Auxx/shapes_cbyears_bOnly_postfit_tt_35_m_sv.pdf Aux_Figure_020.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_mh125_ls.pdf Aux_Figure_114.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_mh125_lc.pdf Aux_Figure_115.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_mh125_muneg_1.pdf Aux_Figure_116.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_mh125_muneg_2.pdf Aux_Figure_117.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_mh125_muneg_3.pdf Aux_Figure_118.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_mh1125_CPV.pdf Aux_Figure_119.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_hMSSM.pdf Aux_Figure_120.pdf
rsync -av --progress ${PAPERREPO}/Auxx/model-dependent_limit_mh125EFT_lc.pdf Aux_Figure_122.pdf
popd;
